// <auto-generated />
using System;
using CEGES_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CEGES_DataAccess.Migrations
{
    [DbContext(typeof(CegesDbContext))]
    [Migration("20211203034215_SeedEquipement")]
    partial class SeedEquipement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CEGES_Core.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entreprises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Pizza Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Aluminium du Québec"
                        });
                });

            modelBuilder.Entity("CEGES_Core.Equipement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("Equipements");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipement");
                });

            modelBuilder.Entity("CEGES_Core.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Groupes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntrepriseId = 1,
                            Nom = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            EntrepriseId = 1,
                            Nom = "Livraison"
                        },
                        new
                        {
                            Id = 3,
                            EntrepriseId = 2,
                            Nom = "Baie-Comeau"
                        },
                        new
                        {
                            Id = 4,
                            EntrepriseId = 2,
                            Nom = "Arvida"
                        },
                        new
                        {
                            Id = 5,
                            EntrepriseId = 2,
                            Nom = "Alma"
                        },
                        new
                        {
                            Id = 6,
                            EntrepriseId = 2,
                            Nom = "Kitimat"
                        },
                        new
                        {
                            Id = 7,
                            EntrepriseId = 2,
                            Nom = "Sept-Îles"
                        },
                        new
                        {
                            Id = 8,
                            EntrepriseId = 2,
                            Nom = "Deschambeault"
                        });
                });

            modelBuilder.Entity("CEGES_Core.Mesure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EquipementId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("CEGES_Core.Periode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Debut")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("CEGES_Core.EquipementConstant", b =>
                {
                    b.HasBaseType("CEGES_Core.Equipement");

                    b.Property<decimal>("Emissions")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.HasDiscriminator().HasValue("EquipementConstant");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            GroupeId = 1,
                            Nom = "Administration",
                            Emissions = 0.0078m
                        },
                        new
                        {
                            Id = 15,
                            GroupeId = 3,
                            Nom = "Réfection des cuves",
                            Emissions = 0.0154m
                        },
                        new
                        {
                            Id = 19,
                            GroupeId = 3,
                            Nom = "Cuves à débrasquer",
                            Emissions = 1.25m
                        },
                        new
                        {
                            Id = 20,
                            GroupeId = 3,
                            Nom = "Moulage et refroisissement",
                            Emissions = 0.59m
                        },
                        new
                        {
                            Id = 31,
                            GroupeId = 4,
                            Nom = "Réfection des cuves",
                            Emissions = 0.862m
                        },
                        new
                        {
                            Id = 35,
                            GroupeId = 4,
                            Nom = "Cuves à débrasquer",
                            Emissions = 2.54m
                        },
                        new
                        {
                            Id = 44,
                            GroupeId = 5,
                            Nom = "Réfection des cuves",
                            Emissions = 0.037m
                        },
                        new
                        {
                            Id = 47,
                            GroupeId = 5,
                            Nom = "Cuves à débrasquer",
                            Emissions = 1.98m
                        },
                        new
                        {
                            Id = 58,
                            GroupeId = 6,
                            Nom = "Moulage et refroisissement",
                            Emissions = 0.74m
                        },
                        new
                        {
                            Id = 66,
                            GroupeId = 7,
                            Nom = "Réfection des cuves",
                            Emissions = 1.24m
                        },
                        new
                        {
                            Id = 68,
                            GroupeId = 7,
                            Nom = "Cuves à débrasquer",
                            Emissions = 8.66m
                        },
                        new
                        {
                            Id = 69,
                            GroupeId = 7,
                            Nom = "Moulage et refroisissement",
                            Emissions = 1.54m
                        },
                        new
                        {
                            Id = 77,
                            GroupeId = 8,
                            Nom = "Réfection des cuves",
                            Emissions = 0.0014m
                        },
                        new
                        {
                            Id = 81,
                            GroupeId = 8,
                            Nom = "Cuves à débrasquer",
                            Emissions = 0.98m
                        },
                        new
                        {
                            Id = 82,
                            GroupeId = 8,
                            Nom = "Moulage et refroisissement",
                            Emissions = 0.547m
                        });
                });

            modelBuilder.Entity("CEGES_Core.EquipementLineaire", b =>
                {
                    b.HasBaseType("CEGES_Core.Equipement");

                    b.Property<decimal>("FacteurConversion")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.Property<string>("UniteMesure")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("EquipementLineaire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupeId = 1,
                            Nom = "Four",
                            FacteurConversion = 0.000143m,
                            UniteMesure = "pizza(s)"
                        },
                        new
                        {
                            Id = 5,
                            GroupeId = 2,
                            Nom = "Yaris 1",
                            FacteurConversion = 0.000184m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 6,
                            GroupeId = 2,
                            Nom = "Yaris 2",
                            FacteurConversion = 0.000184m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 7,
                            GroupeId = 2,
                            Nom = "Leaf 1",
                            FacteurConversion = 0.00000854m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 8,
                            GroupeId = 2,
                            Nom = "Leaf 2",
                            FacteurConversion = 0.00000854m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 9,
                            GroupeId = 2,
                            Nom = "Leaf 3",
                            FacteurConversion = 0.00000854m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 10,
                            GroupeId = 3,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 14,
                            GroupeId = 3,
                            Nom = "Centrale hydroélectrique",
                            FacteurConversion = 0.0987m,
                            UniteMesure = "MWh"
                        },
                        new
                        {
                            Id = 16,
                            GroupeId = 3,
                            Nom = "Scies",
                            FacteurConversion = 0.00048m,
                            UniteMesure = "unités"
                        },
                        new
                        {
                            Id = 18,
                            GroupeId = 3,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.47m,
                            UniteMesure = "coulées"
                        },
                        new
                        {
                            Id = 21,
                            GroupeId = 3,
                            Nom = "Concasseur",
                            FacteurConversion = 4.55m,
                            UniteMesure = "t"
                        },
                        new
                        {
                            Id = 26,
                            GroupeId = 4,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 30,
                            GroupeId = 4,
                            Nom = "Centrale hydroélectrique",
                            FacteurConversion = 0.0987m,
                            UniteMesure = "MWh"
                        },
                        new
                        {
                            Id = 32,
                            GroupeId = 4,
                            Nom = "Scies",
                            FacteurConversion = 0.00048m,
                            UniteMesure = "unités"
                        },
                        new
                        {
                            Id = 34,
                            GroupeId = 4,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.68m,
                            UniteMesure = "coulées"
                        },
                        new
                        {
                            Id = 40,
                            GroupeId = 5,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 43,
                            GroupeId = 5,
                            Nom = "Centrale hydroélectrique",
                            FacteurConversion = 0.0987m,
                            UniteMesure = "MWh"
                        },
                        new
                        {
                            Id = 45,
                            GroupeId = 5,
                            Nom = "Scies",
                            FacteurConversion = 0.00087m,
                            UniteMesure = "unités"
                        },
                        new
                        {
                            Id = 46,
                            GroupeId = 5,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.23m,
                            UniteMesure = "coulées"
                        },
                        new
                        {
                            Id = 48,
                            GroupeId = 5,
                            Nom = "Concasseur",
                            FacteurConversion = 4.98m,
                            UniteMesure = "t"
                        },
                        new
                        {
                            Id = 52,
                            GroupeId = 6,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 57,
                            GroupeId = 6,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.85m,
                            UniteMesure = "coulées"
                        },
                        new
                        {
                            Id = 59,
                            GroupeId = 6,
                            Nom = "Concasseur",
                            FacteurConversion = 6.87m,
                            UniteMesure = "t"
                        },
                        new
                        {
                            Id = 63,
                            GroupeId = 7,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 65,
                            GroupeId = 7,
                            Nom = "Centrale hydroélectrique",
                            FacteurConversion = 0.124m,
                            UniteMesure = "MWh"
                        },
                        new
                        {
                            Id = 67,
                            GroupeId = 7,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.87m,
                            UniteMesure = "coulées"
                        },
                        new
                        {
                            Id = 70,
                            GroupeId = 7,
                            Nom = "Concasseur",
                            FacteurConversion = 3.98m,
                            UniteMesure = "t"
                        },
                        new
                        {
                            Id = 74,
                            GroupeId = 8,
                            Nom = "Transport ferroviaire",
                            FacteurConversion = 0.00098m,
                            UniteMesure = "km"
                        },
                        new
                        {
                            Id = 78,
                            GroupeId = 8,
                            Nom = "Scies",
                            FacteurConversion = 0.00034m,
                            UniteMesure = "unités"
                        },
                        new
                        {
                            Id = 80,
                            GroupeId = 8,
                            Nom = "Centre de coulée",
                            FacteurConversion = 0.68m,
                            UniteMesure = "coulées"
                        });
                });

            modelBuilder.Entity("CEGES_Core.EquipementRelatif", b =>
                {
                    b.HasBaseType("CEGES_Core.Equipement");

                    b.Property<decimal>("Maximum")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.Property<decimal>("Minimum")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.HasDiscriminator().HasValue("EquipementRelatif");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            GroupeId = 1,
                            Nom = "Chauffage",
                            Maximum = 12.8m,
                            Minimum = 1.57m
                        },
                        new
                        {
                            Id = 3,
                            GroupeId = 1,
                            Nom = "Éclairage",
                            Maximum = 1.25m,
                            Minimum = 0.85m
                        },
                        new
                        {
                            Id = 11,
                            GroupeId = 3,
                            Nom = "Calcination",
                            Maximum = 6.45m,
                            Minimum = 1.54m
                        },
                        new
                        {
                            Id = 12,
                            GroupeId = 3,
                            Nom = "Fabrication d'anodes",
                            Maximum = 400.15m,
                            Minimum = 12.98m
                        },
                        new
                        {
                            Id = 13,
                            GroupeId = 3,
                            Nom = "Four à réduction",
                            Maximum = 12.55m,
                            Minimum = 8.98m
                        },
                        new
                        {
                            Id = 17,
                            GroupeId = 3,
                            Nom = "Bain broyé",
                            Maximum = 9.73m,
                            Minimum = 6.075m
                        },
                        new
                        {
                            Id = 22,
                            GroupeId = 3,
                            Nom = "Pyroépurateur",
                            Maximum = 96.239m,
                            Minimum = 53.189m
                        },
                        new
                        {
                            Id = 23,
                            GroupeId = 3,
                            Nom = "Bains de précipitation",
                            Maximum = 9.752m,
                            Minimum = 6.007m
                        },
                        new
                        {
                            Id = 24,
                            GroupeId = 3,
                            Nom = "Broyeur humide",
                            Maximum = 22.733m,
                            Minimum = 12.317m
                        },
                        new
                        {
                            Id = 25,
                            GroupeId = 3,
                            Nom = "Filtreurs",
                            Maximum = 2.984m,
                            Minimum = 1.441m
                        },
                        new
                        {
                            Id = 27,
                            GroupeId = 4,
                            Nom = "Calcination",
                            Maximum = 6.518m,
                            Minimum = 3.171m
                        },
                        new
                        {
                            Id = 28,
                            GroupeId = 4,
                            Nom = "Fabrication d'anodes",
                            Maximum = 124.5m,
                            Minimum = 35.4m
                        },
                        new
                        {
                            Id = 29,
                            GroupeId = 4,
                            Nom = "Four à réduction",
                            Maximum = 154.81m,
                            Minimum = 15.002m
                        },
                        new
                        {
                            Id = 33,
                            GroupeId = 4,
                            Nom = "Bain broyé",
                            Maximum = 11.74m,
                            Minimum = 4.775m
                        },
                        new
                        {
                            Id = 36,
                            GroupeId = 4,
                            Nom = "Pyroépurateur",
                            Maximum = 106.448m,
                            Minimum = 53.845m
                        },
                        new
                        {
                            Id = 37,
                            GroupeId = 4,
                            Nom = "Bains de précipitation",
                            Maximum = 8.286m,
                            Minimum = 5.58m
                        },
                        new
                        {
                            Id = 38,
                            GroupeId = 4,
                            Nom = "Broyeur humide",
                            Maximum = 20.853m,
                            Minimum = 10.637m
                        },
                        new
                        {
                            Id = 39,
                            GroupeId = 4,
                            Nom = "Filtreurs",
                            Maximum = 2.575m,
                            Minimum = 0.488m
                        },
                        new
                        {
                            Id = 41,
                            GroupeId = 5,
                            Nom = "Calcination",
                            Maximum = 10.226m,
                            Minimum = 4.611m
                        },
                        new
                        {
                            Id = 42,
                            GroupeId = 5,
                            Nom = "Fabrication d'anodes",
                            Maximum = 98.4m,
                            Minimum = 22.8m
                        },
                        new
                        {
                            Id = 49,
                            GroupeId = 5,
                            Nom = "Bains de précipitation",
                            Maximum = 9.138m,
                            Minimum = 4.89m
                        },
                        new
                        {
                            Id = 50,
                            GroupeId = 5,
                            Nom = "Broyeur humide",
                            Maximum = 20.168m,
                            Minimum = 10.246m
                        },
                        new
                        {
                            Id = 51,
                            GroupeId = 5,
                            Nom = "Filtreurs",
                            Maximum = 4.879m,
                            Minimum = 1.451m
                        },
                        new
                        {
                            Id = 53,
                            GroupeId = 6,
                            Nom = "Calcination",
                            Maximum = 5.317m,
                            Minimum = 1.315m
                        },
                        new
                        {
                            Id = 54,
                            GroupeId = 6,
                            Nom = "Fabrication d'anodes",
                            Maximum = 124.54m,
                            Minimum = 50.1m
                        },
                        new
                        {
                            Id = 55,
                            GroupeId = 6,
                            Nom = "Four à réduction",
                            Maximum = 138.647m,
                            Minimum = 20.215m
                        },
                        new
                        {
                            Id = 56,
                            GroupeId = 6,
                            Nom = "Bain broyé",
                            Maximum = 11.6m,
                            Minimum = 4.914m
                        },
                        new
                        {
                            Id = 60,
                            GroupeId = 6,
                            Nom = "Pyroépurateur",
                            Maximum = 90.679m,
                            Minimum = 68.506m
                        },
                        new
                        {
                            Id = 61,
                            GroupeId = 6,
                            Nom = "Bains de précipitation",
                            Maximum = 11.053m,
                            Minimum = 6.106m
                        },
                        new
                        {
                            Id = 62,
                            GroupeId = 6,
                            Nom = "Filtreurs",
                            Maximum = 3.691m,
                            Minimum = 1.439m
                        },
                        new
                        {
                            Id = 64,
                            GroupeId = 7,
                            Nom = "Calcination",
                            Maximum = 7.848m,
                            Minimum = 2.359m
                        },
                        new
                        {
                            Id = 71,
                            GroupeId = 7,
                            Nom = "Bains de précipitation",
                            Maximum = 10.667m,
                            Minimum = 6.196m
                        },
                        new
                        {
                            Id = 72,
                            GroupeId = 7,
                            Nom = "Broyeur humide",
                            Maximum = 24.073m,
                            Minimum = 9.74m
                        },
                        new
                        {
                            Id = 73,
                            GroupeId = 7,
                            Nom = "Filtreurs",
                            Maximum = 2.167m,
                            Minimum = 1.228m
                        },
                        new
                        {
                            Id = 75,
                            GroupeId = 8,
                            Nom = "Fabrication d'anodes",
                            Maximum = 16.4m,
                            Minimum = 8.45m
                        },
                        new
                        {
                            Id = 76,
                            GroupeId = 8,
                            Nom = "Four à réduction",
                            Maximum = 122.521m,
                            Minimum = 28.675m
                        },
                        new
                        {
                            Id = 79,
                            GroupeId = 8,
                            Nom = "Bain broyé",
                            Maximum = 8.03m,
                            Minimum = 6.379m
                        },
                        new
                        {
                            Id = 83,
                            GroupeId = 8,
                            Nom = "Pyroépurateur",
                            Maximum = 108.3m,
                            Minimum = 50.36m
                        },
                        new
                        {
                            Id = 84,
                            GroupeId = 8,
                            Nom = "Bains de précipitation",
                            Maximum = 7.907m,
                            Minimum = 5.215m
                        },
                        new
                        {
                            Id = 85,
                            GroupeId = 8,
                            Nom = "Broyeur humide",
                            Maximum = 24.9m,
                            Minimum = 8.98m
                        },
                        new
                        {
                            Id = 86,
                            GroupeId = 8,
                            Nom = "Filtreurs",
                            Maximum = 3.413m,
                            Minimum = 1.311m
                        });
                });

            modelBuilder.Entity("CEGES_Core.Equipement", b =>
                {
                    b.HasOne("CEGES_Core.Groupe", "Groupe")
                        .WithMany("Equipements")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("CEGES_Core.Groupe", b =>
                {
                    b.HasOne("CEGES_Core.Entreprise", "Entreprise")
                        .WithMany("Groupes")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("CEGES_Core.Mesure", b =>
                {
                    b.HasOne("CEGES_Core.Equipement", "Equipement")
                        .WithMany("Mesures")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CEGES_Core.Periode", "Periode")
                        .WithMany("Mesures")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("CEGES_Core.Periode", b =>
                {
                    b.HasOne("CEGES_Core.Entreprise", "Entreprise")
                        .WithMany("Periodes")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("CEGES_Core.Entreprise", b =>
                {
                    b.Navigation("Groupes");

                    b.Navigation("Periodes");
                });

            modelBuilder.Entity("CEGES_Core.Equipement", b =>
                {
                    b.Navigation("Mesures");
                });

            modelBuilder.Entity("CEGES_Core.Groupe", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("CEGES_Core.Periode", b =>
                {
                    b.Navigation("Mesures");
                });
#pragma warning restore 612, 618
        }
    }
}
